spring.application.name=ConcurQueueApplication

Logging= show timestamps and thread names in console
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

ConcurQueue=custom settings (we'll read these in our runner)
concurqueue.producer.count=3
concurqueue.producer.tasks-per-batch=5
concurqueue.worker.pool-size=4
concurqueue.queue.capacity=100
concurqueue.monitor.interval-seconds=5